config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  get "team" => "static_pages#team"
  get "careers" => "static_pages#careers"
  get "privacy" => "static_pages#privacy"
  resources :courses, only: [:index, :show] do
    get "(page/:page)", action: :index, on: :collection, as: ""
    resources :enrollments, only: [:create]
  end
  resources :lessons, only: :show
  resource :dashboard, only: :show do
    get "enrolled/:enrolled_page", action: :show, on: :member, as: "enrolled_page"
    get "taught/:taught_page", action: :show, on: :member, as: "taught_page"
    get "enrolled/:enrolled_page/taught/:taught_page", action: :show, on: :member, as: "both_page"
  end
  namespace :instructor do
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create, :update]
    end
    resources :sections, only: [] do
      resources :lessons, only: [:create, :update]
    end
  end
  get "instructor/courses/:course_id/sections" => redirect("instructor/courses/%{course_id}")
  get "instructor/sections/:section_id/lessons" => redirect {|params|
    course = Section.find(params[:section_id]).course
    "instructor/courses/#{course.id}"
  }

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def team
  end

  def careers
  end

  def privacy
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/careers.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1 box">
			<h2>Careers</h2>
			<p>Forthcoming...</p>
		</div>
	</div>
</div>

app/views/static_pages/home.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1 hero-column">
			<div class="hero">
				<div class="spacer"></div>
				<div class="row centered-row">
					<div class="frosty col-xs-8 col-xs-offset-2 text-center">
						<h1>Learn at home with Learnster</h1>
						<h3>Hundreds of video courses covering a wide range of topics</h3>
						<br>
						<%= link_to "See Courses", courses_path, class: "btn btn-success" %>
					</div>
				</div>
				<div class="spacer"></div>
			</div>
		</div>
	</div>
	<br>
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1 text-center box">
			<div class="row">
				<div class="col-sm-4">
					<%= image_tag "video_icon.svg", class: "icon" %>
					<br>
					<h3>Tons of Topics</h3>
					<br>
					<p>Whether you're interested in web design, journalism, baking, or auto repair, Learnster has something for you.</p>
					<br>
				</div>
				<div class="col-sm-4">
					<%= image_tag "calendar_icon.svg", class: "icon" %>
					<h3>Flexible Pace</h3>
					<br>
					<p>With Learnster, you always go at your own pace. Need to take a break? No problem. Your Learnster classes will be there for you when you return.</p>
					<br>
				</div>
				<div class="col-sm-4">
					<%= image_tag "cash_icon.svg", class: "icon" %>
					<h3>Simple Pricing</h3>
					<br>
					<p>No need to worry about subscription fees and cancellations. Many Learnster courses are free, while the rest can be purchased with a one-time payment and are yours forever.</p>
					<br>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/privacy.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1 box">
			<h2>Privacy Policy</h2>
			<p>Forthcoming...</p>
		</div>
	</div>
</div>

app/views/static_pages/team.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1 box">
			<%= image_tag "obulkin_photo.jpg", size: "200", class: "team-photo pull-left" %>
			<h2>Oleg Bulkin</h2>
			<p>After graduating from Stanford University with a degree in Economics, Oleg spent 9 years working in various internet marketing roles (SEM, SEO, display, video, etc.). He gradually moved into more and more technical marketing roles and has recently quit the field to kick this trend up a notch and pursue a career in web development.</p>
		</div>
	</div>
</div>