config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  get "team" => "static_pages#team"
  get "careers" => "static_pages#careers"
  get "privacy" => "static_pages#privacy"
  resources :courses, only: [:index, :show] do
    get "(page/:page)", action: :index, on: :collection, as: ""
    resources :enrollments, only: [:create]
  end
  resources :lessons, only: :show
  resource :dashboard, only: :show do
    get "enrolled/:enrolled_page", action: :show, on: :member, as: "enrolled_page"
    get "taught/:taught_page", action: :show, on: :member, as: "taught_page"
    get "enrolled/:enrolled_page/taught/:taught_page", action: :show, on: :member, as: "both_page"
  end
  namespace :instructor do
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create, :update]
    end
    resources :sections, only: [] do
      resources :lessons, only: [:create, :update]
    end
  end
  get "instructor/courses/:course_id/sections" => redirect("instructor/courses/%{course_id}")
  get "instructor/sections/:section_id/lessons" => redirect {|params|
    course = Section.find(params[:section_id]).course
    "instructor/courses/#{course.id}"
  }

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.page(params[:page]).per(3)
    return redirect_to courses_path(@courses.num_pages) if params[:page] && params[:page].to_i > @courses.num_pages 
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!

  def new
    @course = Course.new
  end

  def create
    @course = Course.new course_params.merge(user_id: current_user.id)
    if @course.save
      redirect_to instructor_course_path(@course)
    else
      render "new", status: :unprocessable_entity
    end
  end

  def show
    @course = Course.find params[:id]
    return redirect_to course_path(@course) if @course.user != current_user
    @section = Section.new # Used by new section modal
    @lesson = Lesson.new # Used by new lesson modal
  end

  private 
  def course_params 
    params.require(:course).permit(:title, :image, :description, :cost)
  end
end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_course_owner

  def create
    @lesson = Lesson.new lesson_params.merge(section_id: current_section.id)
    if @lesson.save
      redirect_to instructor_course_path(current_section.course)
    else
      @course = current_section.course
      @section = Section.new
      @validation_section = current_section
      render "instructor/courses/show", status: :unprocessable_entity
    end
  end

  def update
    lesson = Lesson.find params[:id]
    return head :forbidden if lesson.section != current_section # Protects against section/lesson mismatch
    lesson.update_attributes(sort_order_position: params[:sort_order_position]) ? head(:ok) : head(:unprocessable_entity)
  end

  private
  def current_section
    @current_section ||= Section.find params[:section_id]
  end

  def require_course_owner
    render text: "Not Allowed: A course can only be modified by its owner", status: :unauthorized if current_section.course.user != current_user
  end

  def lesson_params
    params.require(:lesson).permit(:title, :subtitle, :video)
  end
end

app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_course_owner

  def create
    @section = Section.new section_params.merge(course_id: current_course.id)
    if @section.save
      redirect_to instructor_course_path(current_course)
    else
      @course = current_course
      @lesson = Lesson.new
      render "instructor/courses/show", status: :unprocessable_entity
    end
  end

  def update
    section = Section.find params[:id]
    return head :forbidden if section.course != current_course # Protects against course/section mismatch
    section.update_attributes(sort_order_position: params[:sort_order_position]) ? head(:ok) : head(:unprocessable_entity)
  end

  private
  def current_course
    @current_course ||= Course.find params[:course_id]
  end

  def require_course_owner
    render text: "Not Allowed: A course can only be modified by its owner", status: :unauthorized if current_course.user != current_user
  end

  def section_params
    params.require(:section).permit(:title)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/views/instructor/courses/new.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1 box">
			<h2>Enter Your Course Details</h2>
			<br>
			<%= simple_form_for @course, url: instructor_courses_path do |f| %>
				<%= f.input :title %>
				<%= f.input :image %>
				<%= f.input :description %>
				<%= f.input :cost, input_html: {min: 0.00, step: 0.01, max: 99999.99} %>
				<br>
				<%= f.submit "Create", class: "btn btn-success" %>
			<% end %>
		</div>
	</div>
</div>

app/views/instructor/courses/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="box col-xs-10 col-xs-offset-1 instructor-course-view">
			<h2><%= @course.title %></h2>
			<br>
			<div class="row">
				<div class="col-xs-12 col-sm-8">
					<% if @course.image.present? %>
						<%= image_tag @course.image.thumbnail, class: "course-thumbnail" %>
					<% end %>
					<p><%= @course.description %></p>
				</div>
				<div class="col-xs-12 col-sm-4 text-center">
					<h3><span class="label label-default"><%= @course.cost.zero? ? "Free" : number_to_currency(@course.cost) %></span></h3>
					<br>
					<%= link_to "Preview As Student", course_path(@course), class: "btn btn-success btn-lg" %>
					<br>
					<br>
					<button type="button" id="newSectionModalToggle" class="btn btn-success btn-lg" data-toggle="modal" data-target="#newSectionModal">
						Add Section
					</button>
				</div>
			</div>
			<hr>
			<div class="sortable-sections">
				<% @course.sections.rank(:sort_order).each do |section| %>
					<div class="section" data-update-url="<%= instructor_course_section_path @course, section %>">	
						<h3><span class="glyphicon glyphicon-sort"></span> <%= section.title %></h3>
						<ul class="sortable-lessons">
							<% section.lessons.rank(:sort_order).each do |lesson| %>
								<li data-update-url="<%= instructor_section_lesson_path section, lesson %>">
									<span class="glyphicon glyphicon-sort"></span> <strong><%= lesson.title %></strong> - <%= lesson.subtitle %>
								</li>
							<% end %>
						</ul>
						<button type="button" class="btn btn-success btn-xs newLessonModalToggle" data-toggle="modal" data-target="#newLessonModal" data-form-submit-url="<%= instructor_section_lessons_path section %>" data-section-title="<%= section.title %>" id="newLessonModalToggle-<%= section.id %>">
							Add Lesson
						</button>
					</div>	
				<% end %>
			</div>
		</div>
	</div>
</div>

<!-- Modal for creating new sections -->
<div class="modal fade" id="newSectionModal" tabindex="-1" role="dialog" aria-labelledby="newSectionModal">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="newSectionModalTitle">Enter Your Section Title</h4>
			</div>
			<%= simple_form_for @section, url: instructor_course_sections_path(@course) do |f| %>
				<div class="modal-body">
					<%= f.input :title %>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<%= f.submit "Add Section", class: "btn btn-success" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

<!-- Modal for creating new lessons -->
<div class="modal fade" id="newLessonModal" tabindex="-1" role="dialog" aria-labelledby="newLessonModal" data-validation-recovery="<%= @validation_section.id if @validation_section %>">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close close-modal" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="newLessonModalTitle">Enter Your Lesson Details</h4>
				<h5></h5>
			</div>
			<%= simple_form_for @lesson, url: "#" do |f| %>
				<div class="modal-body">
					<%= f.input :title %>
					<%= f.input :subtitle %>
					<%= f.input :video %>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default close-modal" data-dismiss="modal">Close</button>
					<%= f.submit "Add Lesson", class: "btn btn-success" %>
				</div>
			<% end %>
		</div>
	</div>
</div>