config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  get "team" => "static_pages#team"
  get "careers" => "static_pages#careers"
  get "privacy" => "static_pages#privacy"
  resources :courses, only: [:index, :show] do
    get "(page/:page)", action: :index, on: :collection, as: ""
    resources :enrollments, only: [:create]
  end
  resources :lessons, only: :show
  resource :dashboard, only: :show do
    get "enrolled/:enrolled_page", action: :show, on: :member, as: "enrolled_page"
    get "taught/:taught_page", action: :show, on: :member, as: "taught_page"
    get "enrolled/:enrolled_page/taught/:taught_page", action: :show, on: :member, as: "both_page"
  end
  namespace :instructor do
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create, :update]
    end
    resources :sections, only: [] do
      resources :lessons, only: [:create, :update]
    end
  end
  get "instructor/courses/:course_id/sections" => redirect("instructor/courses/%{course_id}")
  get "instructor/sections/:section_id/lessons" => redirect {|params|
    course = Section.find(params[:section_id]).course
    "instructor/courses/#{course.id}"
  }

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.page(params[:page]).per(3)
    return redirect_to courses_path(@courses.num_pages) if params[:page] && params[:page].to_i > @courses.num_pages 
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!

  def new
    @course = Course.new
  end

  def create
    @course = Course.new course_params.merge(user_id: current_user.id)
    if @course.save
      redirect_to instructor_course_path(@course)
    else
      render "new", status: :unprocessable_entity
    end
  end

  def show
    @course = Course.find params[:id]
    return redirect_to course_path(@course) if @course.user != current_user
    @section = Section.new # Used by new section modal
    @lesson = Lesson.new # Used by new lesson modal
  end

  private 
  def course_params 
    params.require(:course).permit(:title, :image, :description, :cost)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/views/courses/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="box col-xs-10 col-xs-offset-1">
			<h1 class="text-center">Start Learning Today!</h1>
			<br>
			<% @courses.each do |course| %>
				<h3><%= link_to course.title, course_path(course) %></h3>
				<br>
				<div class="row">
					<div class="col-xs-12 col-sm-8">
						<% if course.image.present? %>
							<%= image_tag course.image.thumbnail, class: "course-thumbnail" %>
						<% end %>
						<p><%= course.description %></p>
					</div>
					<div class="col-xs-12 col-sm-4 text-center">
						<%= link_to "Detailed Info", course_path(course), class: "btn btn-success btn-lg" %>
					</div>
				</div>
				<hr>
			<% end %>
			<%= paginate @courses %>
		</div>
	</div>
</div>

app/views/courses/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="box col-xs-10 col-xs-offset-1">
			<h2><%= @course.title %></h2>
			<br>
			<div class="row">
				<div class="col-xs-12 col-sm-8">
					<% if @course.image.present? %>
						<%= image_tag @course.image.thumbnail, class: "course-thumbnail" %>
					<% end %>
					<p><%= @course.description %></p>
				</div>
				<div class="col-xs-12 col-sm-4 text-center">
					<h3><span class="label label-default"><%= @course.cost.zero? ? "Free" : number_to_currency(@course.cost) %></span></h3>
					<br>
					<% if current_user && current_user.enrolled_in?(@course) %>
						<h3><span class="label label-default">You're Enrolled!</span></h3>
					<% elsif @course.cost.zero? %>
						<%= link_to "Enroll", course_enrollments_path(@course), method: :post, class: "btn btn-success btn-lg" %>
						<br>
					<% else %>			
						<%= link_to "Enroll", "#", class: "btn btn-success btn-lg", id: "stripe-enroll", data: {amount: (@course.cost * 100).to_i, key: Rails.configuration.stripe[:publishable_key], description: @course.title + " (" + number_to_currency(@course.cost) + ")"} %>
						<%= form_tag course_enrollments_path(@course), id: "hidden-stripe-form" do %>
							<%= hidden_field_tag "stripe_token" %>
				      	<% end %>
					<% end %>
					<% if current_user == @course.user %>
						<br>
						<%= link_to "Administer Course", instructor_course_path(@course), class: "btn btn-success btn-lg" %>
					<% end %>
				</div>
			</div>
			<hr>
			<% @course.sections.rank(:sort_order).each do |section| %>
				<div class="section">
					<h3><%= section.title %></h3>
					<ul>
						<% section.lessons.rank(:sort_order).each do |lesson| %>
							<%= link_to lesson_path(lesson) do %>
								<li><strong><%= lesson.title %></strong> - <%= lesson.subtitle %></li>
							<% end %>
						<% end %>
					</ul>
				</div>
			<% end %>
		</div>
	</div>
</div>