config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  get "team" => "static_pages#team"
  get "careers" => "static_pages#careers"
  get "privacy" => "static_pages#privacy"
  resources :courses, only: [:index, :show] do
    get "(page/:page)", action: :index, on: :collection, as: ""
    resources :enrollments, only: [:create]
  end
  resources :lessons, only: :show
  resource :dashboard, only: :show do
    get "enrolled/:enrolled_page", action: :show, on: :member, as: "enrolled_page"
    get "taught/:taught_page", action: :show, on: :member, as: "taught_page"
    get "enrolled/:enrolled_page/taught/:taught_page", action: :show, on: :member, as: "both_page"
  end
  namespace :instructor do
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create, :update]
    end
    resources :sections, only: [] do
      resources :lessons, only: [:create, :update]
    end
  end
  get "instructor/courses/:course_id/sections" => redirect("instructor/courses/%{course_id}")
  get "instructor/sections/:section_id/lessons" => redirect {|params|
    course = Section.find(params[:section_id]).course
    "instructor/courses/#{course.id}"
  }

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :user, inverse_of: :courses
  has_many :sections, inverse_of: :course, dependent: :destroy
  has_many :enrollments, inverse_of: :course
  has_many :enrolled_users, through: :enrollments, source: :user

  mount_uploader :image, ImageUploader

  validates :title, presence: true
  validates :description, presence: :true
  validates :cost, presence: :true, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 99999.99}
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :user, inverse_of: :enrollments
  belongs_to :course, inverse_of: :enrollments
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :section, inverse_of: :lessons

  mount_uploader :video, VideoUploader

  include RankedModel
  ranks :sort_order, with_same: :section_id
  
  validates :title, presence: true
  validates :subtitle, presence: true
  validates :video, presence: true

  def next_lesson
    next_lesson = section.lessons.where("sort_order > ?", sort_order).rank(:sort_order).first
    unless next_lesson 
      next_section = section.next_section_with_lessons
      next_lesson = next_section.lessons.rank(:sort_order).first if next_section
    end
    next_lesson
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :course, inverse_of: :sections
  has_many :lessons, inverse_of: :section, dependent: :destroy
  
  include RankedModel
  ranks :sort_order, with_same: :course_id 

  validates :title, presence: true

  def next_section_with_lessons
    next_section = self
    while (next_section)
      next_section = course.sections.where("sort_order > ?", next_section.sort_order).rank(:sort_order).first
      return next_section if next_section && next_section.lessons.present?
    end
    next_section
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :courses, inverse_of: :user, dependent: :destroy
  has_many :enrollments, inverse_of: :user
  has_many :enrolled_courses, through: :enrollments, source: :course

  def enrolled_in?(course)
    enrolled_courses.include?(course)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :store_location

  # Store the previous URL as a user browses around and redirect to it after a sign in or sign up
  private
  def store_location
    session[:previous_path] = request.fullpath unless request.fullpath.include?("/users") || !request.get?
  end

  def after_sign_in_path_for(resource_or_scope)
    return session[:previous_path] || root_path
  end

  def after_sign_up_path_for(resource_or_scope)
    return session[:previous_path] || root_path
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.page(params[:page]).per(3)
    return redirect_to courses_path(@courses.num_pages) if params[:page] && params[:page].to_i > @courses.num_pages 
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def show
    @enrolled_courses = current_user.enrolled_courses.page(params[:enrolled_page]).per(3) 
    @taught_courses = current_user.courses.page(params[:taught_page]).per(3)

    if params[:enrolled_page] && params[:enrolled_page].to_i > @enrolled_courses.num_pages
      params[:taught_page] ? redirect_to(both_page_dashboard_path(@enrolled_courses.num_pages, params[:taught_page])) : redirect_to(enrolled_page_dashboard_path(@enrolled_courses.num_pages))
    elsif params[:taught_page] && params[:taught_page].to_i > @taught_courses.num_pages
      params[:enrolled_page] ? redirect_to(both_page_dashboard_path(params[:enrolled_page], @taught_courses.num_pages)) : redirect_to(taught_page_dashboard_path(@taught_courses.num_pages))
    end
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def create
    course = Course.find params[:course_id]

    unless course.cost.zero?
      amount = (course.cost * 100).to_i # Amount in cents
      Stripe::Charge.create(
        amount: amount,
        source: params[:stripe_token],
        currency: "usd",
        description: "Enrollment in Course #{course.id}: #{course.title}",
        metadata: {user_id: current_user.id},
        statement_descriptor: "Learnster enrollment"
      )
    end

    Enrollment.create user_id: current_user.id, course_id: course.id
    redirect_to course_path(course)
    
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to course_path(course)

  rescue Stripe::StripeError => e
    flash[:error] = "Something went wrong, and you were not charged. Please try again later."
    redirect_to course_path(course)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_enrolled_user_or_owner

  def show
  end

  private
  def current_lesson
    @lesson ||= Lesson.find params[:id]
  end

  def require_enrolled_user_or_owner
    current_course = current_lesson.section.course
    redirect_to course_path(current_course), alert: "You must be enrolled in this course to access the lessons." unless current_user.enrolled_in?(current_course) || current_user.courses.include?(current_course)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def team
  end

  def careers
  end

  def privacy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_devise.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3 col-sm-4 col-sm-offset-4 box">
			<%= yield %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Learnster</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width">
	</head>
	<body>
		<nav class="navbar navbar-inverse">
			<div class="container-fluid">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<%= link_to "Learnster", root_path, class: "navbar-brand"%>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li><%= link_to "See All Courses", courses_path %></li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<% if current_user.present? %>
							<li><%= link_to "My Dashboard", dashboard_path %></li>
							<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
						<% else %>
							<li><%= link_to "Sign In", new_user_session_path %></li>
							<li><%= link_to "Sign Up", new_user_registration_path %></li>
						<% end %>	
					</ul>
				</div>
			</div>
		</nav>
		<div class="container-fluid text-center">
			<noscript>
				<p class="alert alert-danger" role="alert">Warning: Some features on this site require JavaScript to work properly.</p>
			</noscript>
			<% if flash[:alert].present? %>
				<p class="alert alert-danger" role="alert"><%= flash[:alert] %></p>
			<% end %>
			<% if flash[:notice].present? %>
				<p class="alert alert-success" role="alert"><%= flash[:notice] %></p>
			<% end %>
		</div>
		<div class="main-content">
			<%= controller.class.name.include?("Devise") ? render("layouts/devise") : yield %>
		</div>
		<footer class="footer">
			<div class="container-fluid">
				<div class="row">
					<div class="col-xs-12 col-sm-3">
						<b>Teachers</b>
						<br>
						<%= link_to "Add a Course", new_instructor_course_path %>
					</div>
					<div class="col-xs-12 col-sm-3">
						<b>About</b>
						<br>
						<%= link_to "Team", team_path %>
						<br>
						<%= link_to "Careers", careers_path %>
						<br>
						<%= link_to "Privacy Policy", privacy_path %>
					</div>
					<div class="col-xs-12 col-sm-3">
						<b>Contact</b>
						<br>
						o.bulkin@gmail.com
						<br>
						San Francisco, CA 94107
					</div>
					<div class="col-xs-12 col-sm-3 social">
						<b>Social</b>
						<br>
						<%= link_to "https://github.com/obulkin" do %>
							<%= image_tag "github_logo.png", class: "social-button" %>
						<% end %>
						<%= link_to "https://www.linkedin.com/in/obulkin" do %>
							<%= image_tag "linkedin_logo.png", class: "social-button" %>
						<% end %>
					</div>
				</div>
			</div>
		</footer>
	</body>
</html>